Module_10: Added pymango to package manager
abdulraoufatia/DevOps-Course-Starter pull request #16
Opened 2022-08-16 19:52 UTC by abdulraoufatia

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

- Create a MongoDB
- Replacing Trello

2022-10-11 08:23 UTC, JackMead requested changes
Nice work; I can run your app and see my to-dos using Mongo after I fiddled with the dependencies a little, but currently those aren't working and your tests are failing even when we get past that! We should definitely fix those two things up; see my comments below for more info and do reach out if anything's unclear

2022-10-11 08:23 UTC, JackMead commented on pyproject.toml
> +bson = "^0.5.10"
I think this is a mistake - your pipeline is failing your tests because the bson imports aren't working, and pymongo should import the version of Bson it requires automatically so I think this is causing the clash. 

To fix this, I had to run:
```
poetry remove bson
poetry remove pymongo
<deleted the .venv folder>
poetry add pymongo
```

2022-10-11 08:23 UTC, JackMead commented on todo_app/test/test_db.py
> +@pytest.fixture
This fails for me because `pytest` isn't imported - is this relevant/does it even get used anywhere any more?

2022-10-11 08:23 UTC, JackMead commented on todo_app/data/viewmodel.py
> +            if item.status == "In-Progress":
You've changed this but not your view-model test so that test now fails!

2022-10-11 08:23 UTC, JackMead commented on testcosmos.py
> +import pymongo
I'm not quite sure what this file is for: I think it's meant to just be for exploring/developing, which is a helpful practice *but* it shouldn't end up being committed in that case - the remaining code is not relevant to the rest of your system!

2022-10-11 08:23 UTC, JackMead commented on todo_app/data/trello_items.py
> +client = MongoClient(connectionn_string, tlsCAFile=ca)
Good job figuring your way past this issue!

2022-10-11 08:23 UTC, JackMead commented on todo_app/data/trello_items.py
>      return response.json()
Can we get rid of all the old Trello functions now? If they're unused, then keeping them around just provides material to confuse future developers! We can always fall back to Git if we want to recover them

2022-10-11 08:23 UTC, JackMead commented on todo_app/data/trello_items.py
> +def get_all_cards():
I think bringing this into this file makes a lot of sense, nice 👍

2022-10-11 08:23 UTC, JackMead commented on todo_app/data/trello_items.py
> +    # return requests.put(completeing_card_url, params=query_params_complete)
Let's get rid of this rather than just commenting it 😄

2022-10-19 08:22 UTC, abdulraoufatia commented on testcosmos.py
> +import pymongo
Deleted file

2022-10-31 11:53 UTC, JackMead requested changes
Thanks for making those changes - I can see your dependencies are now playing ball but I still see failures in your pipeline and when running the integration test locally. I've left various comments below on how we can fix that (you've unfortunately run into a couple of fairly niche issues!) but feel free to reach out if it's unclear what those suggestions are for 🙂

2022-10-31 11:53 UTC, JackMead commented on todo_app/test/test_app.py
> +# from urllib import response
Rather than commenting this out, let's delete it! We can always recover it from Git's history, but having it here adds cruft for future-you & other people to worry about!

2022-10-31 11:53 UTC, JackMead commented on todo_app/test/test_db.py
> +def test_index_page(client):
This test is still failing in your pipeline! That's possibly because you've got quotes around your connection string in your `.env.test` file - python-dotenv strips those as you'd expect but Docker literally thinks you want quotes in your environment variable so that might be why the schema is rejected - look out for the trailing `.` too

2022-10-31 11:53 UTC, JackMead commented on todo_app/data/mongo_items.py
> +todo_items = db.todo_tasks
This code executing outside a function means it runs as soon as the file is imported, which causes issues for your integration test! The easiest solution here might be to catch this in a function like we had to with environment variables back in M3:
```suggestion
def get_collection():
  ca = certifi.where()
  connectionn_string = os.environ.get("PRIMARY_CONNECTION_STRING")
  client = MongoClient(connectionn_string, tlsCAFile=ca)
  db = client.todo_app
  todo_items = db.todo_tasks 
  return todo_items
```
And then have other parts of this code call `get_collection()` rather than trying to use `todo_items` directly

2022-10-31 11:53 UTC, JackMead commented on todo_app/test/test_db.py
> +    with mongomock.patch(servers=(('mongodb+srv://fakemongo.com', 27017),)):
I believe you just want the server name here:
```suggestion
    with mongomock.patch(servers=(('fakemongo.com', 27017),)):
```

2022-10-31 11:53 UTC, JackMead commented on todo_app/data/mongo_items.py
> +client = MongoClient(connectionn_string, tlsCAFile=ca)
Separately to the below, you're suffering from one of the more annoying bugs I've found through no fault of your own - mongomock mocks the pymongo library in such a way that it fails to intercept individually imported classes/functions; what I mean by that is this fails for me currently but if I switch to:
```suggestion
client = pymongo.MongoClient(connectionn_string, tlsCAFile=ca)
```
Then it helps!

2022-10-31 11:53 UTC, JackMead commented on todo_app/test/test_db.py
> +def test_index_page(client):
That said, there are other issues blocking this too. One is related to what we saw in M3 - the order in which things are loaded. Currently your `mongo_items` file loads the connection _before_ `mongomock` has time to set up the interceptions, so we'll need to adjust that; see comments on that file.

2022-10-31 11:53 UTC, JackMead commented on todo_app/test/test_db.py
> +    assert "Test card" in response.data.decode()
Finally, this assertion says the DB should have a test card, but I can't see anywhere that actually adds that, so I don't expect this to pass! The easiest solution to this is probably to directly add it at the start of this test using your existing function
```python
    create_mongo_item("Test card)
```

2022-11-01 14:50 UTC, abdulraoufatia commented on todo_app/test/test_app.py
> +# from urllib import response
Removed! :) thanks jack

2022-11-12 21:04 UTC, abdulraoufatia commented on todo_app/data/viewmodel.py
> +            if item.status == "In-Progress":
changed this

2022-11-12 21:04 UTC, abdulraoufatia commented on todo_app/data/trello_items.py
>      return response.json()
removed.

2022-11-12 21:06 UTC, abdulraoufatia commented on todo_app/data/mongo_items.py
> +todo_items = db.todo_tasks
Done this for next commit.

2022-11-12 21:06 UTC, abdulraoufatia commented on todo_app/data/mongo_items.py
> +client = MongoClient(connectionn_string, tlsCAFile=ca)
thanks jack - done :)

2022-11-12 21:07 UTC, abdulraoufatia commented on todo_app/test/test_db.py
> +    with mongomock.patch(servers=(('mongodb+srv://fakemongo.com', 27017),)):
Thanks jack - have done this :)

2022-11-12 21:20 UTC, abdulraoufatia commented on todo_app/test/test_db.py
> +    assert "Test card" in response.data.decode()
have added this as an arrange now investigating it further

2022-11-12 21:21 UTC, abdulraoufatia commented on todo_app/test/test_db.py
> +@pytest.fixture
fixed this now and have imported it

2022-12-06 11:38 UTC, CorndelWithSoftwireDevOps approved these changes
Thank you for the resolution of the issues.

There is one comment which has been resolved, but I can still see the commented out code in the file it concerned. This should be simple to clean up

Readme needs expanding on and modifying a bit. I trust it's simple enough that it doesn't need a re-review.

2022-12-06 11:38 UTC, CorndelWithSoftwireDevOps commented on README.md
> +PRIMARY_CONNECTION_STRING = 'zxc'
You will need to expand your `README.md` file to include the setup steps for mongoDB connection. Currently your .env file is an amalgamation of Trello and CosmosDB and it's not clear what the user needs to get either setup going (since they don't connect to both at the same time, in fact **your code update means I can't use Trello. Your new README should reflect that**).

Where would I get the `PRIMARY_CONNECTION_STRING` from?

Your `.env.template` file is also old and could do with an update with new environment variables introduced since.

2022-12-06 11:38 UTC, CorndelWithSoftwireDevOps commented on todo_app/test/test_app.py
> +# from urllib import response
It looks like these are still here. I got a bit confused thinking you commented them to make your build pass, but it looks like you should just delete this file

2022-12-06 23:02 UTC, merged